In [9]:
import numpy as np
import pandas as pd

import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm

In [30]:
## Import Stock Market Data

## Import advertisting dataset
bikeshare = pd.read_csv('..\..\datasets\Bikeshare_hour.csv', index_col='instant')
display(bikeshare)

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,,
1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [31]:
bikeshare[['yr', 'mnth', 'hr', 'weekday', 'workingday', 'holiday']] = bikeshare[['yr', 'mnth', 'hr', 'weekday', 'workingday', 'holiday']].astype('str')
bikeshare.drop(columns=['dteday', 'season', 'yr', 'holiday', 'weekday', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered'], inplace=True)
bikeshare.dtypes

mnth          object
hr            object
workingday    object
weathersit     int64
cnt            int64
dtype: object

In [33]:
exog = bikeshare.drop(columns=['cnt'])
exog = pd.get_dummies(exog, columns=['mnth', 'hr', 'workingday'])
endog = bikeshare.cnt

exog = sm.add_constant(exog)

poisson_model = sm.GLM(endog, exog, faimly=sm.families.Poisson)

poisson_results = poisson_model.fit()

print(poisson_results.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                    cnt   No. Observations:                17379
Model:                            GLM   Df Residuals:                    17342
Model Family:                Gaussian   Df Model:                           36
Link Function:               identity   Scale:                          13271.
Method:                          IRLS   Log-Likelihood:            -1.0713e+05
Date:                Thu, 27 Apr 2023   Deviance:                   2.3013e+08
Time:                        12:34:55   Pearson chi2:                 2.30e+08
No. Iterations:                     3   Pseudo R-squ. (CS):             0.7727
Covariance Type:            nonrobust
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const         4.358e+13   9.65e+13      0.451      0.652   -1.46e+14    2.33e+14
weathersit     -37.5753      1.384    -27.149      0.000     -40.288     -34.863
mnth_1       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_10      -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_11      -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_12      -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_2       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_3       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_4       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_5       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_6       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_7       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_8       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
mnth_9       -4.201e+12   2.18e+13     -0.193      0.847   -4.69e+13    3.85e+13
hr_0          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_1          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_10         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_11         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_12         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_13         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_14         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_15         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_16         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_17         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_18         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_19         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_2          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_20         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_21         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_22         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_23         1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_3          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_4          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_5          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_6          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_7          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_8          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
hr_9          1.819e+12   4.02e+12      0.453      0.651   -6.06e+12     9.7e+12
workingday_0  -4.12e+13   9.91e+13     -0.416      0.678   -2.35e+14    1.53e+14
workingday_1  -4.12e+13   9.91e+13     -0.416      0.678   -2.35e+14    1.53e+14
================================================================================

c:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\base\model.py:127: ValueWarning: unknown kwargs ['faimly']
  warnings.warn(msg, ValueWarning)